### ISSUE TITLE
fetch RC calendar events from ICS URL

### ISSUE THREAD

**Issue by jryio** [gregsadetsky/recurselevision#11]
Some RC test account has its personal calendar URL like this: `https://www.recurse.com/calendar/events.ics?token=<token>`

RCTV server fetches in periodically in the background thanks to #8 

**Server**
- [ ] Background fetch
- [ ] Parse `events.ics` with some python library
- [ ] Convert it to JSON
- [ ] Return it

**SDK**
- [ ] Make an SDK method that actually calls this

**Comment by gregsadetsky** [comment]
re: background fetch, let's use this -->> https://fastapi.tiangolo.com/tutorial/background-tasks/

it's exactly perfect, we can do ttl-caching of the ics file from time to time (every 5 minutes) and just serve app's JS/API requests from the (in memory, or on-disk) cache (of the ICS data)

ics parsing -> https://pypi.org/project/ics/

**Comment by jryio** [comment]
@gregsadetsky thanks!!!

**Comment by jryio** [comment]
@gregsadetsky Turns out that https://pypi.org/project/ics/ does not support recurring events `RRULE` and most of RC events are recurring, so I'm trying this package: https://icalendar.readthedocs.io/en/latest/index.html
